site_name: The Shattering
site_url: https://dlondonmedina.github.io/theshattering/
docs_dir: markdown
site_dir: docs
nav: 
  - Home: index.md
  - Gatherings: ch1.md
theme: material
plugins:
  - privacy